import pytest

pytest.register_assert_rewrite("hil.utils.exception_table")
